version: '3'

services:
  web:
    build:
      context: ./docker/
      dockerfile: web.dockerfile
    container_name: adm-web
    volumes:
      - ./:/var/www
    ports:
      - "8121:80"
    links:
      - app
  app:
    build:
      context: ./docker/
      dockerfile: app.dockerfile
    container_name: adm-app
    volumes:
      - ./:/var/www
    links:
      - db
    ports:
      - "8122:3000"
    environment:
      - DB_PORT=3306
      - DB_HOST=db
  db:
    build:
      context: ./docker/
      dockerfile: db.dockerfile
    container_name: adm-db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dockerApp
    ports:
      - "33062:3306"